name: flutter_cocktail
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6
  http: ^1.6.0
  dio: ^5.9.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/icone/search.svg
    - assets/img/icone/cart1.svg
    - assets/img/icone/add1.svg
    - assets/img/icone/home.svg
    - assets/img/icone/profile.svg
    - assets/img/bibite/soda.png
    - assets/img/cocktail/bloody.png
    - assets/img/cocktail/margarita.png
    - assets/img/cocktail/mojito.png
    - assets/img/cocktail/negroni.png
    - assets/img/cocktail/spritz.png
    - assets/img/condimenti/tabasco.png
    - assets/img/condimenti/worsterstershire.png
    - assets/img/dolcificanti/zucchero.png
    - assets/img/erbe/menta.png
    - assets/img/frutta/lime.png
    - assets/img/spezie/pepe.png
    - assets/img/spezie/sale.png
    - assets/img/spiriti/aperol.png
    - assets/img/spiriti/campari.png
    - assets/img/spiriti/gin.png
    - assets/img/spiriti/rumbianco.png
    - assets/img/spiriti/tequila.png
    - assets/img/spiriti/triplesec.png
    - assets/img/spiriti/vodka.png
    - assets/img/spiriti/vermouth.png
    - assets/img/succhi/succolime.png
    - assets/img/succhi/succopomodoro.png
    - assets/img/vini/prosecco.png
    - assets/img/generic/logo_pnk_nobg.png
    - assets/img/generic/logo_wht_nobg.png
    - assets/img/generic/menu.png
    - assets/img/generic/login.png
    - assets/img/generic/mail.svg
    - assets/img/generic/password.svg
    - assets/img/generic/user.svg
    - assets/img/generic/show.svg
    - assets/img/generic/hide.svg
    - assets/img/generic/registrazione.png













  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gabarito
      fonts:
        - asset: fonts/Gabarito-VariableFont_wght.ttf
